# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wear.Category'),
        ),
    ]
