# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wear', '0002_auto_20170926_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoe',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
